### ISSUE TITLE
Feature request: support ruby language

### ISSUE THREAD

**Issue by magynhard** [mikhail-tin/cucumber-step-mapper-ts#3]
Feature request. I would like to ask for adding ruby language support.

**Comment by mikhail-tin** [comment]
Hi, I have removed this extension from Vs Code Marketplace by some reasons.
I created this extension when I couldn't find nothing for myself in Marketplace, but now I see some good extensions with additional functionality.

**Comment by magynhard** [comment]
Thank you for your reply. 

Unfortunately there is still no solution with ruby support. If someone knows a ruby solution, he might post it here for other googling people.

**Comment by mikhail-tin** [comment]
**entwanderer**,
If you provide to me some kind of example on ruby, probably I can prepare an extension.
it should not takes a lot of time.

**Comment by magynhard** [comment]
That would be awesome.

Here you go:

```
#### example.feature

Feature: Example

Scenario: Just an example
 When the example with "variable" is fine
 Then Mikhail might implement ruby support
```

```
#### example_steps.rb
When("the example with {string} is fine:") do |value_of_variable|
  # some implementation code ...
end

# equivalent implementation with regex style
When(/^the example with "([^"]*)" is fine/) do |value_of_variable|
  # some implementation code ...
end
```

* The feature files (\*.feature) are stored in folder `/features` with arbitrary subfolders.
* The implementation files (\*.rb usually by convention \*_steps.rb) are stored in folder `/features/step_definitions` wit arbitrary subfolders.

Don't hesitate to ask for more information.

(Googled project example: https://github.com/qmetry/cucumber-ruby-example)

**Comment by mikhail-tin** [comment]
Hi 
https://github.com/mikhail-tin/cucumber-step-mapper-ts/blob/ruby/cucumber-mapper-for-ruby-0.1.0.vsix

it works for regular expression .
I will try add support for {int} {string} and other constructions a little bit later.

![image](https://user-images.githubusercontent.com/17845768/36538466-ae466236-17e4-11e8-84a8-cc707c834d65.png)

**Comment by magynhard** [comment]
Thank you very much, it is a pleasure to be able to jump to the steps.

I wonder if you can use the native "Go to Definition" of Visual Studio Code and just register your code for the .feature file extension. So you would be able to use the same shortcut for "Go to Definition" in every place.
