### ISSUE TITLE
It does not work on Mac

### ISSUE THREAD

**Issue by tonylelai** [mikhail-tin/cucumber-step-mapper-ts#4]
This extension does not work on MacBook Pro
macOS High Sierra v 10.13.2
VS Code  Version 1.19.0 (1.19.0)
typescript Version 2.6.2
Node v8.9.3

**Comment by d4nyll** [comment]
I have the same issue. I am using Ubuntu 17.10. My version of VSCode is as follows:

```
Version 1.20.0-insider
Commit f2b21097100fc2fc0e84cc34f453c9a85a49a2bb
Date 2018-02-02T06:17:03.200Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

I have set the `srcPath` and `typeOfSrc` settings in my Workspace setting. `typeOfSrc` is set to `javascript`

**Comment by mikhail-tin** [comment]
Hi, Im going to check all on this week. Thank for your notes.

**Comment by mikhail-tin** [comment]
Hi, I have removed this extension from Vs Code Marketplace by some reasons.
I created this extension when I couldn't find nothing for myself in Marketplace, but now I see some good extensions with additional functionality.
But I added some changes(fixes) and attached the latest version in this repo. 
Also, I have checked this extension on Win7 and Fedora 27. Now it works fine.
Thx.
