### ISSUE TITLE
Feature request: Support for multiple source paths

### ISSUE THREAD

**Issue by ghost** [mikhail-tin/cucumber-step-mapper-ts#5]
I have multiple cucumber projects in my project. I would like to be able to find all step definitions for all these files which are in different folders.

**Comment by mikhail-tin** [comment]
Hi, I have removed this extension from Vs Code Marketplace by some reasons.
I created this extension when I couldn't find nothing  for myself  in Marketplace, but now I see some good extensions with additional functionality.
But I added some changes(Support for multiple source paths and fixes) and attached the latest version in this repo.
